### ISSUE TITLE
<picture> Tag?

### ISSUE THREAD

**Issue by PetersOtto** [GiovanniSalmeri/yellow-figure#1]
Hello GiovanniSalmeri!

I have just a small question.
I found this project from you, because I am searching for a solution to use the html `<picture>`-Tag.

Do you mabe plan to develop a extension for that in the next time? 

Best regards

**Comment by GiovanniSalmeri** [comment]
Hello, I am so sorry that I forgot to answer timely your message. 😞 Anyway, I will think about your proposal, I understand that there are cases in which the the `<picture>` tag could be actually useful. I will keep you informed if in my spare time I write an extension for using it. Cheers

**Comment by PetersOtto** [comment]
Hello Giovanni!

I think the `<picture>` tag is especially important for large images, so that on cell phones do not have to load the large images.

When I build websites, I do it that way, that I have editable (blog entries, portfolio entries ...) and static (startpage, contact ...) areas. I create Fullscreen images as static areas. For these images I have created a Linux Bash file, which resizes and renames all images in one folder and outputs the picture tag for copy & paste. Here I work with ImageMagick. If you want you can have the file. 

For photographers or designers it is important that the images are always displayed perfectly (as well for Retina Displays). From my point of view here the `<picture>` tag would make sense also with smaller pictures.

I have already made myself a few thoughts but I'm not the great coder. 
https://github.com/PetersOtto/yellow-picture

Many greetings and happy coding &#128512;
